# Overview
OpenSCAD project to create a cage that fits in 3 5.25" drive bays and holds 4 3.5" hard drives using rails.

Optionally supports a fan shroud to provide additional airflow to the drives.

# Printing Notes
All parts except the rail are designed to be printed without supports.

I typically print all parts except the rail with typical settings for the material in which they are being printed.
- 5% infill is sufficient

For the rail:
- Plater -> 5% infill
- Plater -> Support on build plate only
- Print Settings -> Layers and perimeters -> Vertical shells -> Perimeters: 3
- Print Settings -> Layers and perimeters -> Quality -> Detect briging perimeters: true
- Print Settings -> Support material -> Support material -> Overhang threshold -> 40
This should cause very little support to be generated by the pegs for the hard drives and the clip for latching into the cage.
The rest of the rail should not require support.

# My Equipment
- Prusa MK3
- PrusaSlicer-2.3.3

# References

Several other projects aided in the creation on this HDD cage.

## Modified Parametric Pin Connectors
This project makes use of [Modified Parametric Pin Connectors](https://www.thingiverse.com/thing:3218332) by [acwest](https://www.thingiverse.com/acwest/designs) on thingiverse.  After testing other fan mounting mechanisms, I liked using this pin and socket mechanism, primarily because even if I end up accidentally breaking a pin, printing out a new part is minutes, not hours.

## Customizable Fan Grill Covers
This project makes use of [Customizable Fan Grill Covers](https://www.thingiverse.com/thing:4837562) by [OutwardB](https://www.thingiverse.com/OutwardB) on thingiverse.

Several preset grills are provided using these settings:

all:
- Frame -> fan preset: 120mm
- Frame -> frame option: full
- Frame -> screw hole chamfer: bottom
- Frame -> min border size in millimeter: 5
- Pattern -> line size in millimeter: 1.6
- Advanced | Frame Setting -> rounded corners: no

crosshair
- Pattern -> grill pattern: crosshair
- Pattern -> line space in millimeter:  19.0

crosshex
- Pattern -> grill pattern: crosshex
- Pattern -> line space in millimeter:  8.0

grid:
- Pattern -> line space in millimeter:  8.0

teardrop:
- Pattern -> line space in millimeter:  8.0
- Pattern -> grill pattern rotation: 180

web:
- Pattern -> grill pattern: web
- Pattern -> line space in millimeter:  19.0

none:
- Frame -> screw hole chamfer: no

To create a custom grill, you can use any STL file that fits the grill pattern with the expectation that the front of the grill is what is facing down on the printer bed and that the center of the grill is at the origin [0, 0, 0] when the STL is loaded into OpenSCAD.
Use the settings describe above if using OutwardB's custom fan grill cover generator, and then make the desired changes, render, and export the STL as fan_cover_custom.stl
Then in OpenSCAD, select "fan_shroud" as the part, grill style of custom.
You will then see the customized fan shroud.
Render it and export the STL.
